// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sengiffddirprlxmmabi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNlbmdpZmZkZGlycHJseG1tYWJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3MDY2MjcsImV4cCI6MjA3MzI4MjYyN30.YR3aE1fKtJ9Ez3g3owsC6KxpkUjWrX_sy4yp-qgHf3g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});