version: '3.8'

services:
  analysis-service:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8000:8000"
    environment:
      - MODEL_URL=${MODEL_URL:-https://sengiffddirprlxmmabi.supabase.co/storage/v1/object/public/sequence-images/models/clip_finetuned_final.pt}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G